In [1]:
import numpy as np

In [2]:
np.sin(90)

0.8939966636005579

In [3]:
np.sinh(10)

11013.232874703393

In [4]:
np.arcsin(1)

1.5707963267948966

In [5]:
np.arcsin(90)

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


nan

In [6]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array.min()

1

In [8]:
array.max()

9

In [9]:
array.argmax()

8

In [10]:
array.argmin()

0

In [12]:
sec1=np.array(np.random.randint(10,20,[4,4]))
sec1

array([[15, 16, 16, 18],
       [14, 14, 14, 14],
       [15, 17, 17, 19],
       [12, 10, 12, 15]])

In [14]:
sec2=np.array(np.random.randint(1,10,[4,4]))
sec2

array([[5, 1, 4, 6],
       [9, 1, 1, 5],
       [5, 5, 6, 2],
       [5, 9, 1, 6]])

In [15]:
np.vstack((sec1,sec2))

array([[15, 16, 16, 18],
       [14, 14, 14, 14],
       [15, 17, 17, 19],
       [12, 10, 12, 15],
       [ 5,  1,  4,  6],
       [ 9,  1,  1,  5],
       [ 5,  5,  6,  2],
       [ 5,  9,  1,  6]])

In [16]:
np.hstack((sec1,sec2))

array([[15, 16, 16, 18,  5,  1,  4,  6],
       [14, 14, 14, 14,  9,  1,  1,  5],
       [15, 17, 17, 19,  5,  5,  6,  2],
       [12, 10, 12, 15,  5,  9,  1,  6]])

In [17]:
np.column_stack((sec1,sec2))

array([[15, 16, 16, 18,  5,  1,  4,  6],
       [14, 14, 14, 14,  9,  1,  1,  5],
       [15, 17, 17, 19,  5,  5,  6,  2],
       [12, 10, 12, 15,  5,  9,  1,  6]])

In [18]:
sec1+sec2

array([[20, 17, 20, 24],
       [23, 15, 15, 19],
       [20, 22, 23, 21],
       [17, 19, 13, 21]])

In [19]:
sec1*sec2

array([[ 75,  16,  64, 108],
       [126,  14,  14,  70],
       [ 75,  85, 102,  38],
       [ 60,  90,  12,  90]])

In [20]:
sec1@sec2

array([[389, 273, 190, 310],
       [336, 224, 168, 266],
       [408, 288, 198, 323],
       [285, 217, 145, 236]])

In [22]:
sec1.dot(sec2)

array([[389, 273, 190, 310],
       [336, 224, 168, 266],
       [408, 288, 198, 323],
       [285, 217, 145, 236]])

In [23]:
sec1.transpose()

array([[15, 14, 15, 12],
       [16, 14, 17, 10],
       [16, 14, 17, 12],
       [18, 14, 19, 15]])

In [24]:
sec1.trace()

61

In [27]:
np.hsplit(sec1,2)

[array([[15, 16],
        [14, 14],
        [15, 17],
        [12, 10]]), array([[16, 18],
        [14, 14],
        [17, 19],
        [12, 15]])]

In [28]:
np.vsplit(sec1,[2,3])

[array([[15, 16, 16, 18],
        [14, 14, 14, 14]]),
 array([[15, 17, 17, 19]]),
 array([[12, 10, 12, 15]])]

In [29]:
np.abs(-100.25)

100.25

In [30]:
np.absolute(-100.25)

100.25

In [31]:
np.all(sec1>0)

True

In [32]:
np.any(sec1<0)

False

In [33]:
np.any(sec1<15)

True

In [34]:
np.round(12.63)

13.0

In [35]:
np.floor(10.96)

10.0

In [36]:
np.ceil(10.23)

11.0