# This is heading 1(H1 TAG)
## (h2 tag)
### (h3 tag)
#### (h4 tag)
##### (h5 tag)
###### (h6 tag)

In [1]:
import numpy as np


In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [3]:
array([1,2,3,4,5])

NameError: name 'array' is not defined

In [4]:
d1=np.array([1,2,3,4,5])

In [5]:
d1.size

5

In [6]:
d1.shape

(5,)

In [7]:
d1.ndim

1

In [8]:
d1

array([1, 2, 3, 4, 5])

In [9]:
d1[1]

2

In [10]:
d1[0:2]

array([1, 2])

In [11]:
d1[0:5]

array([1, 2, 3, 4, 5])

In [12]:
data=np.array(['A',1,'CSE','lakshmi',25,50])
data

array(['A', '1', 'CSE', 'lakshmi', '25', '50'], dtype='<U7')

In [13]:
import time
start_time=time.time()
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]
output=list(map(lambda x,y : x*y,list1,list2))
end_time=time.time()
print("Time Taken by list concept",end_time-start_time)

Time Taken by list concept 0.015610933303833008


In [14]:
import time
start_time1=time.time()
ar1=np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time1=time.time()
print("Time taken by numpy is:",end_time1-start_time1)

Time taken by numpy is: 0.015612602233886719


In [15]:
d2=np.array([[45,74,65],[78,90,45],[34,67,90]])
d2

array([[45, 74, 65],
       [78, 90, 45],
       [34, 67, 90]])

In [16]:
d2.shape

(3, 3)

In [17]:
d2.size

9

In [18]:
d2.ndim

2

In [19]:
d2[0]

array([45, 74, 65])

In [20]:
d2[0,2]

65

In [21]:
d2[1].max()

90

In [22]:
np.max(d2[1])

90

In [23]:
d2[:,2]

array([65, 45, 90])

In [24]:
d2[:,1].max()

90

In [25]:
d2[:,0].min()

34

In [26]:
d2.sum()

588

In [27]:
d2.sum(axis=0)
d2

array([[45, 74, 65],
       [78, 90, 45],
       [34, 67, 90]])

In [28]:
d2.sum(axis=1)

array([184, 213, 191])

In [29]:
d2.sum(axis=0)

array([157, 231, 200])

In [30]:
d3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [31]:
d3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
d3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
d3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
d3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
d3[0,0,1]

2

In [36]:
n=10
for i in range(0,n):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [37]:
for i in np.arange(0,10):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [38]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
for i in range(0,10,0.5):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [40]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [41]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [42]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [43]:
print(np.zeros[2,4])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [44]:
print(np.zeros([2,4]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
print(np.ones([2,4]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [47]:
np.tile(3,[2,2])

array([[3, 3],
       [3, 3]])

In [48]:
d21=np.array([[1,2,3,4,5],[6,7,8,9,10]])
d21

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
add_marks=np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [50]:
final_marks=d21+add_marks
final_marks

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [54]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [56]:
np.random.random(10)

array([0.07308553, 0.13346172, 0.474591  , 0.28770636, 0.26435148,
       0.71479458, 0.71764079, 0.72959154, 0.09087572, 0.05481726])

In [57]:
np.random.randint(10)

0

In [58]:
np.random.randint(10)

1

In [59]:
np.random.randint(10,30)

23

In [60]:
np.random.randint(10,20,30)

array([11, 15, 19, 12, 16, 10, 10, 18, 19, 14, 16, 14, 16, 15, 14, 15, 18,
       19, 10, 14, 19, 14, 18, 14, 15, 17, 11, 11, 13, 15])

In [61]:
np.random.randint(10,25,[4,6])

array([[22, 21, 15, 24, 23, 23],
       [20, 12, 24, 14, 20, 22],
       [18, 13, 23, 22, 19, 18],
       [21, 21, 15, 22, 22, 14]])

In [62]:
np.random.rand(10)

array([0.58220923, 0.66396398, 0.19819365, 0.10457411, 0.43372163,
       0.23294289, 0.35593279, 0.07351279, 0.91033535, 0.23625953])

In [63]:
np.random.rand(1)

array([0.28001125])

In [65]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [68]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])